services: 
  pgsql-db:
    image: "postgres:15-alpine"
    container_name: pgsql-db
    environment: 
      POSTGRES_DB: gocrud
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    command: >
      postgres -c log_statement=all -c log_destination=stderr
    volumes: 
      - './database-volume:/var/lib/postgresql/data:rw'
    ports: 
      - "5488:5432"
